// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mddyirczgyasbqcmgnwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kZHlpcmN6Z3lhc2JxY21nbndjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0NTczMjYsImV4cCI6MjA1MzAzMzMyNn0.hGcjWMDHnorrlAd1psLd7Udicej76pvVdmQAn8C9IAY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);